= APIkit Mule4-1.1.2 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

*May 2, 2018*

== What's New

There are no new features in this version. There are just a few enhancements and bug fixes.

== Compatibility

* Mule Runtime 4.1.2 and later
* Anypoint Studio 7.1.2 and later
* Java Parser RAML 1.0 v1.0.20
* Java Parser RAML 0.8 v0.8.22
* API Console 4.2.0

== Fixed in the Release

* URI params should be exposed as variables.  (APIKIT-1242)
* APIKit unable to parse and validate JSON against schema referenced using $ref at design time. (APIKIT-1225)
* When validating JSON against RAML, there is no obvious way to identify the failing element. (APIKIT-1222)


GitHub RAML Java parser issues fixed in this release:

* Datetime with RFC3339 validates invalid examples. #470
* Get more verbose output when validation fails due to maxLength. #476
* Improve error feedback when a type is invalid. #482
* Incorrect merging of properties when extending from a type. #488
* JSON schema validation error is not precise when using a not normalized URI in a $ref. #474
* Upgrade Jackson to 2.9.5 in v2. #484
* validate() in TypeDeclaration doesn't work as expected when validating a blank space. #485