= Amazon RDS Connector Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: amazon-rds-connector-release-notes-mule-4.adoc
:keywords: release notes, amazon rds, rds, connector

_Select_

*February 2018*

Amazon Relational Database Service (Amazon RDS) makes it easy to set up, operate, and scale a relational database in the cloud. The Anypoint Connector for Amazon RDS provides connectivity to the Amazon Relational Database Service (Amazon RDS) API, enabling you to interface with Amazon RDS to provide cost-efficient and resizable capacity while automating time-consuming administration tasks such as hardware provisioning, database setup, patching, and backups.

Starting with v.1.0.0, the RDS connector is licensed commercially with Anypoint Platform as with other Select connectors.

== 1.1.0

*February 21, 2018*

Release notes for version 1.1.0 of the Amazon RDS connector.

=== Compatibility

The Amazon RDS Connector is compatible with:

|===
|Application/Service|Version
|Mule Runtime|4.1.0
|Amazon Java SDK for RDS|v1.11.172
|Java|1.8 or higher
|Anypoint Studio|7.0 or higher
|===

=== Fixed in this Release

AWS connectors shared a common library for the supported region endpoints that caused an issue when two different AWS connectors were used in a Mule app. This version fixes this issue.


== 1.0.0

*November 18, 2017*

Release notes for version 1.0.0 of the Amazon RDS connector.

=== Compatibility

The Amazon RDS Connector is compatible with:

|===
|Application/Service|Version
|Mule Runtime|4.0.0
|Amazon Java SDK for RDS|v1.11.172
|Java|1.8 or higher
|Anypoint Studio|7.0 or higher
|===

=== Features

* Built with the new AnyPoint SDK (Extensions Framework) v1.0.0-rc-SNAPSHOT.
* Built with AWS SDK v1.11.172
* Support for Temporary Credentials - A checkbox named Try Default AWS Credentials Provider Chain has been added to the Global Configuration Elements. If selected, the connector will first try to obtain the credentials from an AWS environment.
* Support for Retry Policy - The connector can be configured with a Reconnection strategy that is provided in the Advanced tab
* The following operations are supported:

** *DB Instances*
*** CreateDBInstance
*** CreateDBInstanceReadReplica
*** DeleteDBInstance
*** DescribeDBInstances
*** ModifyDBInstance
*** RebootDBInstance
*** RestoreDBInstanceFromDBSnapshot
*** RestoreDBInstanceToPointInTime
*** StartDBInstance
*** StopDBInstance

**  *DB Snapshots*
*** CreateDBSnapshot
*** DeleteDBSnapshot
*** DescribeDBSnapshots
*** ModifyDBSnapshot

**  *Events*
*** DescribeEvents

**  *Reserved DB Instances*
*** DescribeReservedDBInstances
*** DescribeReservedDBInstancesOfferings
*** PurchaseReservedDBInstancesOffering


=== Fixed in this Release

Initial version.


== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]