= Amazon EC2 Connector Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: amazon-ec2-connector-release-notes-mule-4.adoc
:keywords: release notes, amazon ec2, ec2, connector

*February 2018*

_Select_

Amazon Elastic Compute Cloud (Amazon EC2) provides scalable computing capacity in the Amazon Web Services (AWS)
cloud. The Anypoint Connector for Amazon EC2 provides connectivity to the Amazon Elastic Compute Cloud (Amazon EC2) API enabling you to interface with Amazon EC2 to launch as many or as few virtual servers as you need, configure security and networking, and manage storage.

== 2.1.0

*February 21, 2018*

Release notes for version 2.1.0 of the Amazon EC2 connector.

=== Compatibility

The Amazon EC2 Connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |4.1.0 or later
|Amazon Java SDK for EC2 |v1.11.134
|Java |1.8.0_x
|Anypoint Studio |7.0 or later
|===

=== Fixed in this Release

AWS connectors shared a common library for the supported Region Endpoints that caused an issue when two different AWS connectors were used in a Mule app. This version fixes this issue.

== 2.0.0

*November 18, 2017*

Release notes for version 2.0.0 of the Amazon EC2 connector.

=== Compatibility

The Amazon EC2 Connector is compatible with:

|===
|Application/Service|Version
|Mule Runtime|4.0.0 and later
|Amazon Java SDK for EC2|v1.11.134
|Java|1.8.0_x
|Anypoint Studio|7.0 and later
|===

=== Features

* Migrated to Mule 4.0.0 runtime.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]