= HL7 EDI Connector Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: hl7-connector-release-notes.adoc

*January 2018*

_Premium_

== 3.1.0

*January 3, 2018*

Version 3.1.0 provides bug fixes and greatly improved usability.

HL7 EDI Connector v3.1.0 is compatible with the following:

[%header,cols="30a,70a"]
|===
|Application/Service |Version
|Mule Runtime |3.6.0 and later
|Anypoint Studio |5.0.0 and later
|HL7 |v2.1, v2.2, v2.3.1, v2.3, v2.4, v2.5, v2.5.1, v2.6, 2.7, 2.7.1, 2.8, 2.8.1
|===

=== New Features

* Separate sets of schemas for lax validation (all data elements treated as strings; length, repetition count, and usage restrictions not enforced).
* Drops numeric prefixes used on segment keys.
* Uses MSH segment definition from (first) configured schema.
* Allows configuration of ACK message schema.
* Provides a tool to generate a simplified schema definition based on one or more sample documents.

=== Fixed in this Release

* Apply configured character encoding when writing.
* Throw an exception when the wrong data type is found when writing (previously just stopped the write).
* Correct handling of message structure segment groups with optional leading segments.
* Correct handling of choice groupings of segments.

=== Backward Compatibility

Version 3.0.0 always used numeric position prefixes on segment keys (such as "01_MSH"). This has been disabled by default in 3.1.0, so that the segment key is normally just the segment tag (modified with a numeric suffix, if necessary because the segment is used in multiple locations within the same level of the message structure). For compatibility with 3.0.0 mappings you can turn off the "Disable numeric prefixes for data keys" configuration option (`identKeys="false"`).

=== Known Issue

* The `validateHL7Version` configuration option is not working and results in a NullPointerException when trying to read a message with this option enabled.

== 3.0.0

*January 6, 2017*

Release notes for version 3.0 of the HL7 EDI Connector. Anypoint Connector for HL7 is a collection of features that facilitates integration with healthcare systems by providing the tools needed to easily create, read, and transform HL7 version v2.x messages within Mule.

HL7 EDI Connector v3.0.0 is compatible with the following:

[%header,cols="30a,70a"]
|===
|Application/Service |Version
|Mule Runtime |3.6.0 and later
|Anypoint Studio |5.0.0 and later
|HL7 | v2.1, v2.2, v2.3, v2.3.1, v2.4, v2.5, v2.5.1, v2.6, v2.7, v2.7.1, v2.8, v2.8.1
|===

* Extension segments supported using overlay or custom schemas, or by generic handling for segments matching a pattern.
* Parsing throws an exception when the message is not properly formatted or an error occurs when reading the input stream.
* Fatal errors in parsing (as per configuration) result in acknowledgment code 'AR' (for Application Reject) in the ACK message generated by the parse; non-fatal errors result in acknowledgment code 'AE'.

=== Fixed in this Release

There are no bug fixes in this release.

== See Also

* https://mulesoft.github.io/mule-hl7-connector/[HL7 Technical Reference]
* xref:3.1@healthcare-toolkit::index.adoc[Healthcare Toolkit]
* xref:connector/hl7-mllp-connector-release-notes.adoc[HL7 MLLP Release Notes]
* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]