= Microsoft Dynamics NAV Connector Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: microsoft-dynamics-nav-connector-release-notes.adoc
:keywords: release notes, connector, dynamics-nav

*December 2016*

_Select_

The Microsoft Dynamics NAV Connector enables Mule applications to interact with the Microsoft Dynamics NAV Web Services versions 2013 R2, 2015, 2016.

xref:3.9@mule-runtime::microsoft-dynamics-nav-connector.adoc[Microsoft Dynamics NAV Connector User Guide]

== 1.0.1

*December 13, 2016*

=== Compatibility

[%header, cols=","]
|===
|Software |Version
|Mule Runtime EE |3.7.x or higher
|Java|1.7 or higher
|Dynamics NAV version|2013 R2,2015,2016
|===


=== Features

No new features.


== Fixed in this release

* XML External Entities (XXE) vulnerability - By default, XML parsers are weakly configured thus enabling XML External Entity attack (for example, disclosure of confidential data, denial of service, server side request forgery) when the application parses XML input. To prevent XXE,  DTDs (External Entities) have been completely disabled in all the XML parsers used by the connector.

== Known Issues

None.


== 1.0.0

*September 30, 2016*

=== Compatibility

[%header, cols=","]
|===
|Software |Version
|Mule Runtime EE |3.7.x or higher
|Java|1.7 or higher
|Dynamics NAV version|2013 R2,2015,2016
|===


=== Features

* NTLM Authentication - Allows you to authenticate Microsoft Dynamics NAV via NT LAN Manager.
* OAuth 2.0 Authentication - Allows you to authenticate Microsoft Dynamics NAV via OAuth 2.0 Access Token.
* OData Query - Executes an OData query against one of the published page services or one of the published query services.
* Page Operation - Execute an operation of one of the published Page SOAP services.
* Codeunit Operation - Execute an operation of one of the published Codeunit SOAP services.


== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]