= Microsoft SharePoint 2013 Connector Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: release notes, connectors, sharepoint

*April 2017*

_Select_

*Guide*: xref:3.9@mule-runtime::microsoft-sharepoint-2013-connector.adoc[Microsoft SharePoint 2013 Connector]


== 2.3.0

*April 4, 2017*

Fixes and features in this release:

- Added specific operation for updating files metadata named: "File Update Metadata".
- Added specific operation that allows attaching a file to a list item named: "Attach File".
- Provide authentication mechanism using OKTA based federated identity.
- Provide authentication mechanism using Kerberos.
- Added  HTTP and NTLM proxy support.
- Fixed pagination issue for "List Item Query" operation.

=== Known Issues

- *FileQuery* and *FolderQuery* operations are not supported when interacting with Sharepoint Online.


== 2.2.1

*Dec 14, 2016*

Fixes and features in this release:

- Logging in works correctly. Previously, under specific conditions, logging in could throw a 403 error because some cookies were missing in the login request. Now the connector correctly handles those cookies.

== 2.2.0

*Sep 12, 2016*

Fixes and features in this release:

- Added new connection strategy to allow provide STS token.
- Fixing dependency versioning to avoid multiple proxy classes issue.

== 2.1.12

*Jul 6, 2016*

Fixes and features in this release:

- Fixed bug when using native query with file query operation.
- Fixed SharepointFile POJO to avoid 'LinkingUrl' issues.

== 2.1.11

*Mar 31, 2016*

Fixes and features in this release:

- Support dealing with taxonomy fields.
- Handling 403 due to token expiration through connector's operations.
- Usability improved when creating/updating multi-value lookup fields.
- Inconsistency in relative URL path for file operations fixed.

== 2.1.10

*Feb 10, 2016*

Fixes and features in this release:

- Fixed memory issue when uploading big objects (at local files or in-memory).
- Supporting object's names (in addition to IDs) at list CRUD operations.
- Allowing to use datetime values at query filters.

== 2.1.9

*Oct 19, 2015*

Changes in this release:

- Added compatibility for Online and Claims authentication when using Java 8 (Mule 3.7+ only).
- Added support again for older Mule Runtimes (3.5+), Java 7 or greater is required for all Mule versions.

== 2.1.7

*June 3, 2015*

Fixed in this release:

* When the global redirector returned a URL containing an unencoded space character, an exception occurred during connection testing and while establishing connectivity with SharePoint online. The content of the redirect location is not required by the connector, so it is no longer followed.

== 2.1.6

*May 12, 2015*

Fixed in this release:

* Fixed an issue where the HTTP proxy settings defined for a Mule instance were not being honored by the SharePoint connector.

== 2.1.5

*May 8, 2015*

Fixed in this release:

* Fixed an issue where authenticating against sub site collections was not working.
* Fixed an issue where unknown attributes in JSON responses were preventing successful de-serialization.

*Note*: Versions 2.1.3 - 2.1.4 released internally with no changes to the product.

== 2.1.2

*May 7, 2015*

Fixed in this release:

* Fixed an issue when connecting to SharePoint online where unknown fields were causing responses to not be parsed correctly.
* Fixed a compatibility issue between the connector and Studio 5.1.2 due to library version conflicts.
* Renamed connector description in Studio palette to differentiate between SharePoint 2013 and 2010 versions.
* Moved connector into new Select category from Standard.

== 2.1.1

*April 3, 2015*

This release has the same compatibility and features of version 2.1.0.

Fixed in this release:

Fields returned by queries to SharePoint Online that are new and therefore unexpected by the response schema no longer cause exceptions during de-serialization.

== 2.1.0

*February 4, 2015*

Release Notes for the Microsoft SharePoint 2013 connector Version 2.1.

=== Compatibility

The Microsoft SharePoint 2013 connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |3.6 and later
|Anypoint Studio |January 2015
|Microsoft SharePoint |2013
|===

=== Features

Added support for Anypoint Studio 3.6 release, allowing the user interface for each supported authentication scheme to be specialized, and exposing only the configuration properties required for that scheme.

=== Fixed in This Release

Improved help-text for claims authentication configuration to aid understanding of configuration.

=== Known Issues

Improved help-text for claims authentication configuration to aid understanding of configuration.

== 2.0.0

*December 1, 2014*

Release Notes for Microsoft SharePoint 2013 Connector Version 2.0.

=== Compatibility

The Microsoft SharePoint 2013 connector is compatible with:

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |3.5.X
|Anypoint Studio |October 2014
|Microsoft SharePoint |2013
|===

=== Features

* *SharePoint 2013 API* - Broad support for the SharePoint 2013 REST API, including specific operations for Lists & List Items, and Files & Folders. Flexibility to invoke any other API method using the ResolveObject and ResolveCollection operations.
* *Lists & List Items* - Ability to query and manipulate Lists or any List-derived type such as Document Libraries, Picture Lists, and to manage the items within those lists.
* *Files & Folders* - Manage folders and files in any SharePoint library, including the ability to perform advanced workflow operations such as check-out, check-in, publish, unpublished, and recycle.
* *DataSense and DSQL Support* - Full support for DataSense to expose the input and output schema of operations for entities, making it simple to discover the API during development.
* *Improved Test Connection Troubleshooting* - Provides more robust Test Connection functionality in the connector including detailed and helpful error messages for the most common configuration and connectivity problems.
* *Claims Authentication* - Provides support for claims-based authentication, allowing flexibility of the authentication model choice for ADFS-enabled enterprises.
* *NTLM Authentication* - NTLM authentication is now more robust and widely compatible with more domain controller configurations.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]