= Microsoft Dynamics CRM Connector Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: release notes, dynamics, crm, connector

*September 2018*

_Select_

The Microsoft Dynamics Customer Relationship Management (CRM) connector lets you access the Microsoft Dynamics CRM SOAP Organization Service. You can add this connector to an Anypoint Studio flow and in Design Center.

== 3.1.0

*September 26, 2018*

=== Compatibility

[%header, cols=","]
|===
|Application/Service|Version
|Mule Runtime|Mule Enterprise Edition 4.0.0 and 4.1.0 and later
|Anypoint Studio|Only works with Studio 7.0.0 and newer
|Dynamics CRM version|2013, 2015, 2016
|===

=== Features

This version contains the following features:

 * Kerberos connection provider
 * Deleted Object trigger - Queries the audit table to retrieve all deleted objects of specified type
 * New Object trigger - Queries the specified field type table to retrieve all of the new created objects
 * Modified Object trigger - Queries the specified field type table to retrieve all of the fresh modified objects

=== Fixed in this release

* WinOpportunity request was not supported. Fixed by adding specific handling of the request.

=== Known Issues

None.

== 3.0.0

*April 10, 2018*

=== Compatibility

[%header%autowidth.spread]
|===
|Application/Service |Version
|Mule Runtime |Mule Enterprise Edition 4.0.0 and 4.1.0 and later
|Anypoint Studio |Only works with Studio 7.0.0 and later
|Dynamics CRM version |2013, 2015, 2016
|===

=== Features

Same as 2.9.1 (last release)

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]
