= Paypal Connector Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: mule-paypal-anypoint-connector-release-notes.adoc
:keywords: paypal, connector

*August 2015*

_Community_

The PayPal Connector facilitates connections between Mule integration and PayPal. The PayPal Connector v3.0 lets you perform the operations in PayPal's https://developer.paypal.com/docs/classic/api/[NVP and SOAP API Reference]. The connector as of now only supports Signature API credential type of authentication.

*Connector Guide*: xref:3.7@mule-runtime::mule-paypal-anypoint-connector.adoc[PayPal Anypoint Connector]

== 3.0.1

*August 2015*

=== Features

None.

=== Fixes

None.

=== Known Issues

None.

== 3.0.0

*July 31, 2015*

=== Compatibility

The PayPal connector 3.0 is compatible with the following applications:

[%header,cols="2*"]
|===
|Application/Service |Version
|Mule Runtime |3.7.0 or later
|PayPal |Classic SOAP API version 2.0
|===

=== Features

* Added support for all the standard operations and SOAP endpoints as per PayPal's https://developer.paypal.com/docs/classic/api/[NVP and SOAP API Reference]. Use of the API depends on the PayPal account being used.
* Added support for Signature API credentials. The API Signature is infused into the SOAP header for every call.

This version of the connector uses a SOAP Connect feature in 3.7.0 and is not backward compatible with the earlier version of the connector.

=== Fixes

None.

=== Known Issues

As of now authentication is only supported using Signature API credentials. The Certificate API credentials is not supported. Refer to PayPal's https://developer.paypal.com/docs/classic/api/apiCredentials/[Creating and managing NVP/SOAP API credentials] for more details.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]
* See the http://mulesoft.github.io/paypal-connector/[PayPal Connector Technical Reference].