= Redis Connector Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: redis-connector-release-notes.adoc
:keywords: cluster, redis, release notes, connector, object store

*August 2017*

_Select_

https://redis.io/[Redis] is an open source, advanced key-value store.
It is often referred to as a data structure server since keys can contain strings, hashes, lists, sets, and sorted sets.

The Redis Connector offers complete support for its CRUD API.

xref:3.9@mule-runtime::redis-connector.adoc[Redis Connector User Guide]

== 4.1.1

*August 22, 2017*

=== Compatibility

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime | 3.6 and later
|Redis server | 2.8.x, 3.0.x, and 3.2.x
|===

=== Features

No new features.

=== Fixed in this Release

* *DEL Command not exposed* . In past versions the connector didn't list the DEL command into the available commands list. Now it's exposed and works as expected.


== 4.1.0

*February 21, 2017*

=== Compatibility

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime | 3.6 and later
|Redis server | 2.8.x, 3.0.x, and 3.2.x
|===

=== Features

* Added Redis HGETALL command.

== 4.0.0

*July 22, 2016*

=== Compatibility

[%header%autowidth.spread]
|===
|Software |Version
|Mule Runtime | 3.6 and later
|Redis server | 2.8.x, 3.0.x, and 3.2.x
|===

=== Features

* Moved connector to "Select" category.
* Current Redis commands supported by this connector through its operations:
+
DEL EXPIRE GET HEXISTS HGET HKEYS HSET HSETNX KEYS LPOP LPUSH LPUSHX MULTI PSUBSCRIBE PUBLISH RPOP RPUSH RPUSHX SADD SET SETNX SPOP SRANDMEMBER ZADD ZRANGE
+
* Added *entryTTL* to connector's config. This is default time to live to be set on keys stored through connector or when connector is used as an object store.
* Removed *defaultPartitionName* from connector's configuration as it is not used any more.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]