= Anypoint Analytics Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: analytics, release, notes

*January 2017*

== Compatibility

Anypoint Analytics is compatible with all hardware and software as described in xref:3.9@mule-runtime::hardware-and-software-requirements.adoc[Hardware and Software Requirements], as well as API Manager v1.0 and later.

== Mule Compatibility

Anypoint Analytics are compatible with Mule 3.9; however, you need to add the following properties to your project for APIs to be compatible with Analytics in Mule 3.9:

[source,text,linenums]
----
anypoint.platform.analytics_base_uri=https://analytics-ingest.anypoint.mulesoft.com
anypoint.platform.platform_base_uri=https://anypoint.mulesoft.com/apiplatform
anypoint.platform.coreservice_base_uri=https://anypoint.mulesoft.com/accounts
anypoint.platform.contracts_base_uri=https://anypoint.mulesoft.com/apigateway/ccs
----

== 2.3.0

*January 27, 2017*

This release includes metrics visualization not only focused on the view stand on API service protected by the MuleSoft Gateway but also on results returned by the Gateway. This can functionality is exposed on the overview dashboard, custom chars and API Manager reports.

== 2.2.0

*January 13, 2017*

This release is a maintenance release including UI improvements and bug fixing.

* Fixed navigation panel visualization
* Chat Y axis numeric visualization automatically precision adjustment
* Better layout adjustment on browser font resize
* Charts labels rendered at the bottom to avoid overlapping with charts

== 2.1.0

*November 18, 2017*

This release includes several improvements to align API Analytics to the new concepts introduced as part of Crowd release:

* Support for environments
+
Reports and custom dashboards are generated per-environment.
* The API has been updated to be environment-aware.
** The Events API supports environments using a new set of resource paths, while maintaining backwards-compatibility by keeping the current resource paths functional.
** Data is filtered based on the current environment or the "Unclassified" pseudo-environment.
* API Consumer analytics now appear in Exchange.
* The enforcement of 100 requests/second for Events API is now in place.

The release also addresses UI visualization issues with API Consumer and API Analytics.

== 2.0.0

*October 21, 2017*

This release introduces bug fixes:
 - API Event report creation makes used of the browser timezone to define the time selection range.
 - Solves problem that prevented persistence of the "average" metric during dashboard creation.

This release also includes a major re-achitecture on the API Event backend. Effective starting with this release onward, the Analytics Event API provides a one month retention policy instead of 3 months for event and a maximum of 20,000 events per request is enforced.

== 1.21.1

*June 3, 2017*

This release introduces usability and UI layout improvements and bug fixes.

== 1.21.0

*May 6, 2017*

The Analytics release introduces the following capabilities:

* Dashboarding capability and a significantly improved user experience and charts for API Consumer analytics
* Ability to download consumer analytics charts, change dashboard layout, and selectively compare metrics for selected APIs

== 1.20.1

*December 3, 2016*

The Analytics 1.20.1 release enables the alerting engine for API alerts functionality. The API Alerts functionality is described on the xref:api-manager::using-api-alerts.adoc[API Manager] page.

This release also includes following UX improvements and bug fixes:

* AS-659: Correct permissions for child organization(s) when the API version is accessed in the API administration page.

== 1.20.0

*November 19, 2016*

The Analytics 1.20.0 release introduces the alerting engine for API alerts functionality.

This release also includes following UX improvements and bug fixes:

* AP-2677: Correct reporting of error when API access status is revoked
* AP-2638: Display API version on API consumer charts
* AP-2676, 2667, 2678: UX improvement to improve rendering when API list or API names are long
* AP-2672: Remove redundant API calls when requesting tier change

== 1.18.0

*October 11, 2016*

This release introduces the API Consumer Analytics feature which lets an application owner view the API metrics pertaining to the API calls made by an application.
This release also includes a bugfix to the Analytics charts in the API administration page. In the “Top Apps” tab in API Analytics chart the user will now be able to view the breakdown of the API requests for the selected API by the top 5 applications calling the selected API version.

== 1.17.1

*August 11, 2016*

This release includes the following feature enhancements and bug fixes :

* Date range selection for API reports
** Added *Data available from* date for API Analytics data to the Anypoint Analytics *Manage Reports* and *Create Report* pages to indicate the date range for which API Analytics reports can be generated.
** The *No API data available for this data source* warning message now displays if the period selected for a report is outside the API Analytics data availability period.
* Report parameter selection improvements:
** Reporting period of 90 days has been added as one of the drop-down options when generating API reports.
** UI improvements and fixes have been added to enable scrolling through a full list of APIs when generating API Analytics reports.
* Anypoint Analytics data archival time period update:
** Data older than 90 days is archived.
** Reporting of API Analytics data is temporarily limited to a 90-day period. For more information, see https://support.mulesoft.com/s/article/Service-Interruption-07-27-2016-Error-Retrieving-API-Analytics-Data[Service Interruption 07/27/2016 - Error Retrieving API Analytics Data].


*Note:* Releases from 1.12.1 to 1.17.0 were internal bug fix releases.

== 1.12.0

*April 23, 2016*

This release includes several backend infrastructure and functional enhancements to support analytics and usage tracking for upcoming product releases.

== 1.11.0

*February 27, 2016*

This release includes the following feature additions:

* Infrastructure enhancements and optimization.
* Limiting reports API provides results based on a configurable number of rows.

=== Fixed in This Release

* AS-585 - Operational readiness for big customers

== 1.10.1

*January 23, 2016*

This release includes following feature additions:

* OAuth tokens are now supported in addition to JWT for calling the Anypoint Analytics Query and Reports APIs.
* Going to the analytics homepage directly without a validation token now redirects the user to the Anypoint Platform login page.

=== Fixed Issues

* AS-254 - Analytics page does not load and react accordingly when the user is not logged in.
* AS-560 - Allow API calls using OAuth token (deprecate usage of JWT token.)

== 1.10.0

*December 19, 2015*

* To allow correlation between Anypoint Analytics and third-party systems, the `event_id` property
set by the API Gateway (from `message.id`) is now propagated through the system.
* Performing a sign out from the Analytics section of the Anypoint Platform now correctly signs out and redirects to the sign in page.
* OAuth tokens are now supported in addition to JWT for calling the Anypoint Analytics Query and Reports APIs.

== 1.9.0

*December 12, 2015*

* Performance tuning in the ingest system, providing greater ability to handle burst load from API gateways.
* Improved presentation of empty data ranges for API analytics charts, making it more obvious when no data is available.

== See Also

* https://forums.mulesoft.com[MuleSoft Forum]
* https://support.mulesoft.com[Contact MuleSoft Support]