= API Notebook Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

== API Notebook 1.2.1

July 15, 2017

This release focuses on usability and fixes bugs in examples.

== Resolved Issues

* Fixed an issue that prevented API Notebook example text from expanding properly.
* Fixed a problem with API Notebook examples running correctly.
* Fixed the issue with the visibility of an outline of the button and tooltip, which is now hidden after the user clicks the button.
* Fixed an issue that showed the Text Cells menu but did not support any actions.
* Fixed an issue that displayed the next parameter in the sample window when a body having more than one object was added.


== API Notebook 1.2.0

June 17, 2017

This release focuses on a few RAML 1.0-related improvements and bug fixes.

=== Resolved Issues

* Fixed an issue that caused an error that prevented adding some APIs as an API client in Notebook.
* Fixed an issue with loading a RAML 1.0 API and lack of details in the error reporting.
* Fixed an issue that caused the API Notebook to make an invalid suggestions for available methods in some cases.
* Fixed an issue preventing you from deleting a code cell after a text cell.
* Fixed a CSS issue with executing a code cell that produced an inordinately long, partially displayed error message that you could not scroll horizontally.
* Fixed an issue preventing “{proxy: false}” from working.
* Fixed a UI issue preventing the example field from expanding properly.

=== Improvements

* Bumped JS parser version to https://github.com/raml-org/raml-js-parser-2/releases/tag/1.1.18[1.1.18]
* Added support for queryString introduced in RAML 1.0.
* Added support for the Pass Through security scheme introduced in RAML 1.0.