= Runtime Manager Agent 1.6.1 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, agent, release notes

_Enterprise Edition_

*January 4, 2017*

Runtime Manager Agent 1.6.1 provides a new downloadable zip file to easily update Runtime Manager Agent. Download the Runtime Manager agent from the following URL.

https://support.mulesoft.com/s/downloads

You must supply your Anypoint login and password to access this page.

*Runtime Manager Agent Install Guide*: xref:runtime-manager::installing-and-configuring-runtime-manager-agent.adoc[installing and configuring Runtime Manager Agent]

== Compatibility

[%header,cols="2*a",width=70%]
|===
|Software|Version
|Mule Runtime|3.6.n, 3.7.n, 3.8.n
|API Gateway|2.n and above
|Runtime Manager | V2.0 + For complete server Dashboards and Flow Management
|===

[NOTE]
====
Version 1.6.0 (as a minimum) is required to access features released as part of Runtime Manager Cloud V2.0+.
It's also required to access Runtime Manager in the Anypoint Platform Private Cloud Edition V 1.0 & V1.5

Onprem V1.5 currently does not include monitoring functionality, Flow Management or Insight, but will be available in a future release.
====

== Hardware and Software Requirements

No change.

== Improvements and resolved issues

* [CHHYBRID-2388] Enhanced Payload cloning to avoid corrupting streams while Event Tracking is enabled.
* [CHHYBRID-2376] Fixed date parsing when the user locale is not english.
* [CHHYBRID-2368] Fixed disk buffer file corruption under high load.
* [CHHYBRID-2342] REST API call to '/mule/agent' reports mule started flag correctly.
* [CHHYBRID-2298] Fixed Flows retrieval when an application fails to deploy.
* [AGENT-374] Enhanced Mule Agent Plugin upgrader message when is not installed.
* [AGENT-372] Removed SLF4J warning message from upgrader.
* [AGENT-371] Fixed the encryption feature of the Mule Agent Plugin.


== Known Issues

None

== Migration Guide

See xref:runtime-manager::installing-and-configuring-runtime-manager-agent.adoc#updating-a-previous-installation[updating the Runtime Manager agent].

== See Also

* xref:runtime-manager::runtime-manager-agent.adoc[Runtime Manager Agent]
* https://support.mulesoft.com[Contact MuleSoft]