= Runtime Manager Agent 1.6.4 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, agent, release notes

_Enterprise Edition_

*March 27, 2017*

Runtime Manager Agent 1.6.4 provides a new downloadable zip file to easily update Runtime Manager Agent. Download the Runtime Manager agent from the following URL.

https://support.mulesoft.com/s/downloads

You must supply your Anypoint login and password to access this page.

*Runtime Manager Agent Install Guide*: xref:runtime-manager::installing-and-configuring-runtime-manager-agent.adoc[installing and configuring Runtime Manager Agent]

== Compatibility

[%header,cols="2*a",width=70%]
|===
|Software|Version
|Mule Runtime|3.6.n, 3.7.n, 3.8.n
|API Gateway|2.n and above
|Runtime Manager | V2.0
|===

[NOTE]
====
Version 1.6.0 (as a minimum) is required to access features released as part of Runtime Manager Cloud V2.0+.
It's also required to access Runtime Manager in the Anypoint Platform Private Cloud Edition V 1.0 & V1.5
====

== Hardware and Software Requirements

No change.

== Improvements and resolved issues

* CHHYBRID-2663: Logging a warn when auth proxy response with a successful status code
* CHHYBRID-2666: Fixed log line condition check

== Known Issues

None

== Migration Guide

See xref:runtime-manager::installing-and-configuring-runtime-manager-agent.adoc#updating-a-previous-installation[updating the Runtime Manager agent].

== See Also

* xref:runtime-manager::runtime-manager-agent.adoc[Runtime Manager Agent]
* https://support.mulesoft.com[Contact MuleSoft]