= Runtime Manager Agent 1.5.3 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: runtime-manager-agent-1.5.3-release-notes.adoc
:keywords: mule, agent, release notes

_Enterprise Edition_

*November 7, 2016*

Runtime Manager Agent 1.5.3 provides a new downloadable zip file to easily update Runtime Manager Agent. Download the Runtime Manager agent from the following URL.

https://support.mulesoft.com/s/downloads

You must supply your Anypoint login and password to access this page.

*Runtime Manager Agent Install Guide*: xref:runtime-manager::installing-and-configuring-runtime-manager-agent.adoc[installing and configuring Runtime Manager Agent]

== Compatibility

[%header,cols="2*a",width=70%]
|===
|Software|Version
|Mule Runtime|3.6.n, 3.7.n, 3.8.n
|API Gateway|2.n and above
|Runtime Manager | V1.5.0 + For Insight and Dashboards
|===

[NOTE]
====
This version (as a minimum) is required to access features released as part of Runtime Manager Cloud V1.5+.
It's also required to access Runtime Manager in the Anypoint Platform Private Cloud Edition V 1.0 & V1.5

Onprem V1.5 only currently does not include monitoring functionality or insight, but will be available in a future release.
====

== Hardware and Software Requirements

No change.

== Improvements and resolved issues

* Host name verification enabled in the Web socket transport.
* Flag added to enable SSL verification for Splunk.
* Support for Mule Agent registration with TLSv1.2 and JVM 1.7. Core Services certificate trust enhancement.
* Fixed the mule-agent.yml generation when using a proxy during registration.


== Known Issues

* SE-4508 - Add a MuleSoft NTP server to retrieve the server date


== Migration Guide

See xref:runtime-manager::installing-and-configuring-runtime-manager-agent.adoc#updating-a-previous-installation[updating the Runtime Manager agent].

== See Also

* xref:runtime-manager::runtime-manager-agent.adoc[Runtime Manager Agent]
* https://support.mulesoft.com[Contact MuleSoft]