= Runtime Manager Agent 1.4.0 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: runtime-manager-agent-1.4.0-release-notes.adoc
:keywords: mule, agent, 1.3, release notes

_Enterprise Edition_

*April 04, 2016*

Runtime Manager Agent 1.4.0 provides a new downloadable zip file to easily update Runtime Manager Agent. Download the Runtime Manager agent from the following URL.

https://support.mulesoft.com/s/downloads

You must supply your Anypoint login and password to access this page.

*Runtime Manager Agent Install Guide*: link:/runtime-manager/installing-and-configuring-mule-agent[installing and configuring Runtime Manager Agent]

== Compatibility

[%header,cols="2*a",width=70%]
|===
|Software|Version
|Mule Runtime|3.6.n and 3.7.n
|API Gateway|2.n
|===

== Hardware and Software Requirements

No change.

== Features in this Release

* Support for static IP addresses: Agent can now support specific static addresses.

* Addition of an external handler to manage monitoring service tracked beans

== Deprecated Features and Functionality

None.


== Fixed Issues

AGENT-275  -  Remove the /mule/agent/ping endpoint since it's not used and causes the mule to exit

AGENT-277  -  Retrieve the correct Mule and GW version for the unified Mule Runtime 3.8.0

AGENT-278  -  The tracking tests are failing with a org/apache/http/ssl/TrustStrategy class not found error

AGENT-284  -  Runtime Manager Agent isn't detecting that the 3.8.0-M1 Mule Runtime is a unified runtime

AGENT-297  -  Configuring REST transport with custom key store isn't using the given file

AGENT-286  -  Report the runtime as Mule on server registration for Unified Runtimes


== Known Issues

None.

== See Also

* xref:runtime-manager::runtime-manager-agent.adoc[Runtime Manager Agent]
* https://support.mulesoft.com[Contact MuleSoft]