= Runtime Manager Agent 1.4.1 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: mule, agent, release notes

_Enterprise Edition_

*May 14, 2016*

Runtime Manager Agent 1.4.1 provides a new downloadable zip file to easily update Runtime Manager Agent. Download the Runtime Manager agent from the following URL.

https://support.mulesoft.com/s/downloads

You must supply your Anypoint login and password to access this page.

*Runtime Manager Agent Install Guide*: xref:runtime-manager::installing-and-configuring-runtime-manager-agent.adoc[installing and configuring Runtime Manager Agent]

== Compatibility

[%header,cols="2*a",width=70%]
|===
|Software|Version
|Mule Runtime|3.6.n, 3.7.n, 3.8.n
|API Gateway|2.n
|===

== Hardware and Software Requirements

No change.

== Deprecated Features and Functionality

None.


== Fixed Issues

* [AGENT-305] - Support the new version of Hazelcast implemented on Mule 3.8.0

* [AGENT-306] - Upgrade the registration connection of the Runtime Manager Agent to Hybrid to use TLS 1.2

* [CHHYBRID-1544] - GA - Alerts - server / servergourp / cluster - *-down condition being triggered twice in linux and windows

* [SE-3571] - Unable to pair the sever with ARM

* [SE-3683] - Intermittence on servers status: 'Disconnected','Connected' and 'Running'

* [AGENT-304] - Runtime Manager Agent - bind to IP address


== Known Issues

None.

== See Also

* xref:runtime-manager::runtime-manager-agent.adoc[Runtime Manager Agent]
* https://support.mulesoft.com[Contact MuleSoft]