= Runtime Manager 2.0 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: runtime-manager-2.0-release-notes.adoc
:keywords: arm, runtime manager, release notes

The Anypoint Runtime Manager V2.0, is scheduled for release on November 19th. +
This release includes new and granular troubleshooting functionality such as *Insight* for hybrid users, *flow management* and more granular monitoring graphs so users detect the source of their issues more quickly.

== Hardware and Software Requirements

No change.

== Compatibility

Agent plugins integration is compatible with the following runtime versions:

[cols="2*a"]
|===
|Mule | 3.6.x and above.
|Availability | Cloud only.
|API GateWay | 2.x and above for API Analytics
|Runtime Manager Agent | xref:runtime-manager-agent/runtime-manager-agent-1.5.0-release-notes.adoc[1.5.0 and above] for Insight and xref:runtime-manager-agent/runtime-manager-agent-1.6.0-release-notes.adoc[1.6.0 and above] for xref:runtime-manager::flow-management.adoc[Flow Management] and xref:runtime-manager::insight.adoc[all metrics charts]
|===


== Features and Functionality

* *Insight for Hybrid Users*: xref:runtime-manager::insight.adoc[Insight] gives users the ability to troubleshoot their applications for performance and health related issues at a granular level, thus enabling users to determine the root cause of an issue quickly and efficiently. This is now available for all users.
* *Flow Management*: Users will have the ability to manage their problematic flows in runtime. They can now just disable a flow without disrupting the entire application.
* *Monitoring V2.0*:  This release contains granular monitoring charts for metrics that are pertinent to On-Premises servers and are hence used by Hybrid users. +
The new charts include:

** Garbage Collection
** Heap/Non-Heap
** Load average
** Thread count.

Additionally alerts have been set for Load Average and Thread count.

[NOTE]
--
Flow management and monitoring V2.0 functionality is only available for integration applications deployed On-Premises, but management occurs through a cloud console.
--

== Deprecated Features or Functionality

None.