= Mule Management Console 3.8.0
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: mule-management-console-3.8.0.adoc
:keywords: release notes, mmc mule management console

The Mule Management Console, also known as MMC, is a platform for managing Mule applications deployed on premises. Currently, no new functionality is being added to the MMC, this release includes only bug fixes and security fixes. Hybrid & cloud users can check out our latest monitoring & management tool xref:runtime-manager::cloudhub.adoc[Runtime Manager].

[NOTE]
The V3.8 version of MMC is compatible with Mule runtime V3.5 and above.


== May 27, 2016 Release
== Resolved

* Trying to delete a node from a cluster directly from the cluster view may cause a DB corruption.
* TLS configuration is directly obtained from the mule.
* Performance improvements related to deployments.
* Security updates.
* Other minor bug fixes.


== Known Issues

*Attention JDK 1.7 users:*

If you have apps built with Mule runtime 3.8 and you use JDK 1.7, then TLS 1.2 is not supported. It is recommended that you update your JDK to 1.8 to support this security protocol. Starting June 30th, 2016 users using TLSV1.0 will be out of PCI compliance for security reasons. In order to be meet the compliance requirements, Mule V3.8 and MMC V3.8 by default work with TLS V1.2 (approved version). However users using JDK 1.7 will experience that it points to TLSV1.0, which is technically out of compliance. It is highly recommended that you upgrade to JDK 1.8.

In the event that it is not possible to upgrade JDK to 1.8, you can manually configure Mule 3.8 to point to TLS V1.0. See xref:3.8@mule-runtime::tls1-0-migration.adoc[TLS 1.0 Migration] for steps on how to configure this setting. Keep in mind that you should implement the inverse change as what's described in this document, changing the TLS version 1.2 to 1.0

MMC users will need to download MMC version *3.8 HF1*, this version specifically helps users with Mule V3.8 and JDK 1.7 point to TLS V1.0 instead of V1.2, so just updating MMC to this version should solve this problem.

In the event that you later choose to upgrade your JDK version to 1.8, you can continue using MMC V3.8 HF 1