= Mule Management Console 3.8.3
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: mule-management-console-3.8.3.adoc
:keywords: release notes, mmc mule management console

The Mule Management Console, also known as MMC, is a platform for managing Mule applications deployed on premises. Currently, no new functionality is being added to the MMC, this release includes only bug fixes and security fixes.

[NOTE]
Version 3.8.3 of MMC is compatible with Mule runtime v3.x starting with version 3.5.


== Resolved

* SE-5408 - Wrong application name displayed for business events
* SE-4762 - MMC doesn't correctly escape flow names
* SE-4582 - MMC pagination for any listing does not work properly when filtering.
* SE-4133 - log4j2 appender for scripts is not present in log configuration
* SE-3312 - Unregistered servers show ${project.version} as Agent version
* SE-1823 - Alert notification for Thread Pool type filter is not sending email messages
* SE-181 - No email notifications generated by MMC
* SE-1659 - Survivors space max size is incorrectly reported
* SE-1582 - MMC fails to send to email if MS Exchange server requires authentication on SMTP
* SE-846 - MMC Displays MaxMemory and Total Available Memory without decimals
* SE-533 - Alert notifications with the filter 'Type' not working
* SE-6195 - Session Id stripped from clear text logs

== Known Issues

No new known issues with this release