= Anypoint Platform for Pivotal Cloud Foundry 1.5.1 Release Notes
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The Anypoint Platform for PCF solution is a fully integrated solution that enables organizations to design, develop, deploy, manage and operate APIs, connectivity apps and microservices within the fully automated and transparent infrastructure provided by  https://pivotal.io/platform[Pivotal Cloud Foundry]. The different deployment scenarios that Runtime Manager supports are described in detail here: xref:runtime-manager::deployment-strategies.adoc[Deployment Strategies].

== System Requirements

See xref:1.5@private-cloud::system-requirements.adoc[About Minimum System Requirements] information on the minimum system requirement.

== Compatibility

This version of Anypoint Platform for PCF is compatible with the following:

[%header%autowidth.spread]
|===
|Component |Version
|Mule Runtime |3.8.1 and later
|Pivotal Cloud Foundry |1.7.x and 1.8.x
|===

== Features

This release adds the following feature:

* **PCF Metrics**: enables you to specify usage limits for development, production and staging environments from Ops Manager. Using PCF Metrics, you can also collect and view usage metrics for Mule applications running on PCF.